//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munin.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Munin.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munin IRC Client.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC Client.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        // Encryption Setup
        public static string EncryptionSetup_Title => ResourceManager.GetString("EncryptionSetup_Title", resourceCulture) ?? "";
        public static string EncryptionSetup_Header => ResourceManager.GetString("EncryptionSetup_Header", resourceCulture) ?? "";
        public static string EncryptionSetup_Description => ResourceManager.GetString("EncryptionSetup_Description", resourceCulture) ?? "";
        public static string EncryptionSetup_WillBeEncrypted => ResourceManager.GetString("EncryptionSetup_WillBeEncrypted", resourceCulture) ?? "";
        public static string EncryptionSetup_ServerConfigs => ResourceManager.GetString("EncryptionSetup_ServerConfigs", resourceCulture) ?? "";
        public static string EncryptionSetup_NickServSasl => ResourceManager.GetString("EncryptionSetup_NickServSasl", resourceCulture) ?? "";
        public static string EncryptionSetup_ChatHistory => ResourceManager.GetString("EncryptionSetup_ChatHistory", resourceCulture) ?? "";
        public static string EncryptionSetup_AllSettings => ResourceManager.GetString("EncryptionSetup_AllSettings", resourceCulture) ?? "";
        public static string EncryptionSetup_CreatePassword => ResourceManager.GetString("EncryptionSetup_CreatePassword", resourceCulture) ?? "";
        public static string EncryptionSetup_ConfirmPassword => ResourceManager.GetString("EncryptionSetup_ConfirmPassword", resourceCulture) ?? "";
        public static string EncryptionSetup_Warning => ResourceManager.GetString("EncryptionSetup_Warning", resourceCulture) ?? "";
        public static string EncryptionSetup_Enable => ResourceManager.GetString("EncryptionSetup_Enable", resourceCulture) ?? "";
        public static string EncryptionSetup_Skip => ResourceManager.GetString("EncryptionSetup_Skip", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordEmpty => ResourceManager.GetString("EncryptionSetup_PasswordEmpty", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordTooShort => ResourceManager.GetString("EncryptionSetup_PasswordTooShort", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordMismatch => ResourceManager.GetString("EncryptionSetup_PasswordMismatch", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordWeak => ResourceManager.GetString("EncryptionSetup_PasswordWeak", resourceCulture) ?? "";
        public static string EncryptionSetup_SkipConfirmTitle => ResourceManager.GetString("EncryptionSetup_SkipConfirmTitle", resourceCulture) ?? "";
        public static string EncryptionSetup_SkipConfirmMessage => ResourceManager.GetString("EncryptionSetup_SkipConfirmMessage", resourceCulture) ?? "";
        public static string EncryptionSetup_Failed => ResourceManager.GetString("EncryptionSetup_Failed", resourceCulture) ?? "";
        
        // Unlock Dialog
        public static string Unlock_Title => ResourceManager.GetString("Unlock_Title", resourceCulture) ?? "";
        public static string Unlock_Header => ResourceManager.GetString("Unlock_Header", resourceCulture) ?? "";
        public static string Unlock_Description => ResourceManager.GetString("Unlock_Description", resourceCulture) ?? "";
        public static string Unlock_MasterPassword => ResourceManager.GetString("Unlock_MasterPassword", resourceCulture) ?? "";
        public static string Unlock_Button => ResourceManager.GetString("Unlock_Button", resourceCulture) ?? "";
        public static string Unlock_ForgotPassword => ResourceManager.GetString("Unlock_ForgotPassword", resourceCulture) ?? "";
        public static string Unlock_ResetAll => ResourceManager.GetString("Unlock_ResetAll", resourceCulture) ?? "";
        public static string Unlock_EnterPassword => ResourceManager.GetString("Unlock_EnterPassword", resourceCulture) ?? "";
        public static string Unlock_WrongPassword => ResourceManager.GetString("Unlock_WrongPassword", resourceCulture) ?? "";
        public static string Unlock_TooManyAttempts => ResourceManager.GetString("Unlock_TooManyAttempts", resourceCulture) ?? "";
        public static string Unlock_AttemptsCount => ResourceManager.GetString("Unlock_AttemptsCount", resourceCulture) ?? "";
        public static string Unlock_ResetWarning => ResourceManager.GetString("Unlock_ResetWarning", resourceCulture) ?? "";
        public static string Unlock_ResetConfirmTitle => ResourceManager.GetString("Unlock_ResetConfirmTitle", resourceCulture) ?? "";
        public static string Unlock_ResetFinalConfirm => ResourceManager.GetString("Unlock_ResetFinalConfirm", resourceCulture) ?? "";
        
        // Main Window
        public static string MainWindow_AddServer => ResourceManager.GetString("MainWindow_AddServer", resourceCulture) ?? "";
        public static string MainWindow_JoinChannel => ResourceManager.GetString("MainWindow_JoinChannel", resourceCulture) ?? "";
        public static string MainWindow_SendMessage => ResourceManager.GetString("MainWindow_SendMessage", resourceCulture) ?? "";
        public static string MainWindow_Users => ResourceManager.GetString("MainWindow_Users", resourceCulture) ?? "";
        public static string MainWindow_Channels => ResourceManager.GetString("MainWindow_Channels", resourceCulture) ?? "";
        public static string MainWindow_Servers => ResourceManager.GetString("MainWindow_Servers", resourceCulture) ?? "";
        public static string MainWindow_Search => ResourceManager.GetString("MainWindow_Search", resourceCulture) ?? "";
        
        // Add Server Dialog
        public static string AddServer_Title => ResourceManager.GetString("AddServer_Title", resourceCulture) ?? "";
        public static string AddServer_ServerName => ResourceManager.GetString("AddServer_ServerName", resourceCulture) ?? "";
        public static string AddServer_Address => ResourceManager.GetString("AddServer_Address", resourceCulture) ?? "";
        public static string AddServer_Port => ResourceManager.GetString("AddServer_Port", resourceCulture) ?? "";
        public static string AddServer_UseSSL => ResourceManager.GetString("AddServer_UseSSL", resourceCulture) ?? "";
        public static string AddServer_Nickname => ResourceManager.GetString("AddServer_Nickname", resourceCulture) ?? "";
        public static string AddServer_Username => ResourceManager.GetString("AddServer_Username", resourceCulture) ?? "";
        public static string AddServer_RealName => ResourceManager.GetString("AddServer_RealName", resourceCulture) ?? "";
        public static string AddServer_Password => ResourceManager.GetString("AddServer_Password", resourceCulture) ?? "";
        public static string AddServer_AutoConnect => ResourceManager.GetString("AddServer_AutoConnect", resourceCulture) ?? "";
        public static string AddServer_Channels => ResourceManager.GetString("AddServer_Channels", resourceCulture) ?? "";
        
        // Settings Dialog
        public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture) ?? "";
        public static string Settings_General => ResourceManager.GetString("Settings_General", resourceCulture) ?? "";
        public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", resourceCulture) ?? "";
        public static string Settings_Security => ResourceManager.GetString("Settings_Security", resourceCulture) ?? "";
        public static string Settings_Notifications => ResourceManager.GetString("Settings_Notifications", resourceCulture) ?? "";
        public static string Settings_AutoLock => ResourceManager.GetString("Settings_AutoLock", resourceCulture) ?? "";
        public static string Settings_AutoLockMinutes => ResourceManager.GetString("Settings_AutoLockMinutes", resourceCulture) ?? "";
        public static string Settings_ChangePassword => ResourceManager.GetString("Settings_ChangePassword", resourceCulture) ?? "";
        public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture) ?? "";
        public static string Settings_ThemeDark => ResourceManager.GetString("Settings_ThemeDark", resourceCulture) ?? "";
        public static string Settings_ThemeLight => ResourceManager.GetString("Settings_ThemeLight", resourceCulture) ?? "";
        public static string Settings_FontSize => ResourceManager.GetString("Settings_FontSize", resourceCulture) ?? "";
        public static string Settings_Timestamps => ResourceManager.GetString("Settings_Timestamps", resourceCulture) ?? "";
        public static string Settings_DesktopNotifications => ResourceManager.GetString("Settings_DesktopNotifications", resourceCulture) ?? "";
        public static string Settings_SoundNotifications => ResourceManager.GetString("Settings_SoundNotifications", resourceCulture) ?? "";
        
        // Status Messages
        public static string Status_Connecting => ResourceManager.GetString("Status_Connecting", resourceCulture) ?? "";
        public static string Status_Connected => ResourceManager.GetString("Status_Connected", resourceCulture) ?? "";
        public static string Status_Disconnected => ResourceManager.GetString("Status_Disconnected", resourceCulture) ?? "";
        public static string Status_Reconnecting => ResourceManager.GetString("Status_Reconnecting", resourceCulture) ?? "";
        public static string Status_ConnectionFailed => ResourceManager.GetString("Status_ConnectionFailed", resourceCulture) ?? "";
        
        // Context Menu
        public static string ContextMenu_Copy => ResourceManager.GetString("ContextMenu_Copy", resourceCulture) ?? "";
        public static string ContextMenu_Paste => ResourceManager.GetString("ContextMenu_Paste", resourceCulture) ?? "";
        public static string ContextMenu_SelectAll => ResourceManager.GetString("ContextMenu_SelectAll", resourceCulture) ?? "";
        public static string ContextMenu_PrivateMessage => ResourceManager.GetString("ContextMenu_PrivateMessage", resourceCulture) ?? "";
        public static string ContextMenu_Whois => ResourceManager.GetString("ContextMenu_Whois", resourceCulture) ?? "";
        public static string ContextMenu_Kick => ResourceManager.GetString("ContextMenu_Kick", resourceCulture) ?? "";
        public static string ContextMenu_Ban => ResourceManager.GetString("ContextMenu_Ban", resourceCulture) ?? "";
        public static string ContextMenu_Op => ResourceManager.GetString("ContextMenu_Op", resourceCulture) ?? "";
        public static string ContextMenu_DeOp => ResourceManager.GetString("ContextMenu_DeOp", resourceCulture) ?? "";
        public static string ContextMenu_Voice => ResourceManager.GetString("ContextMenu_Voice", resourceCulture) ?? "";
        public static string ContextMenu_DeVoice => ResourceManager.GetString("ContextMenu_DeVoice", resourceCulture) ?? "";
        
        // Script Manager
        public static string ScriptManager_Title => ResourceManager.GetString("ScriptManager_Title", resourceCulture) ?? "Script Manager";
        public static string ScriptManager_OpenFolder => ResourceManager.GetString("ScriptManager_OpenFolder", resourceCulture) ?? "Open Folder";
        public static string ScriptManager_ReloadAll => ResourceManager.GetString("ScriptManager_ReloadAll", resourceCulture) ?? "Reload All";
        public static string ScriptManager_EditorTab => ResourceManager.GetString("ScriptManager_EditorTab", resourceCulture) ?? "Editor";
        public static string ScriptManager_ListTab => ResourceManager.GetString("ScriptManager_ListTab", resourceCulture) ?? "Scripts";
        public static string ScriptManager_TriggerTab => ResourceManager.GetString("ScriptManager_TriggerTab", resourceCulture) ?? "Triggers";
        public static string ScriptManager_QuickActionsTab => ResourceManager.GetString("ScriptManager_QuickActionsTab", resourceCulture) ?? "Quick Actions";
        public static string ScriptManager_Files => ResourceManager.GetString("ScriptManager_Files", resourceCulture) ?? "Files";
        public static string ScriptManager_NewScript => ResourceManager.GetString("ScriptManager_NewScript", resourceCulture) ?? "New Lua Script";
        public static string ScriptManager_NewTrigger => ResourceManager.GetString("ScriptManager_NewTrigger", resourceCulture) ?? "New Trigger File";
        public static string ScriptManager_Delete => ResourceManager.GetString("ScriptManager_Delete", resourceCulture) ?? "Delete";
        public static string ScriptManager_NoFileSelected => ResourceManager.GetString("ScriptManager_NoFileSelected", resourceCulture) ?? "No file selected";
        public static string ScriptManager_Save => ResourceManager.GetString("ScriptManager_Save", resourceCulture) ?? "Save";
        public static string ScriptManager_Run => ResourceManager.GetString("ScriptManager_Run", resourceCulture) ?? "Run";
        public static string ScriptManager_Output => ResourceManager.GetString("ScriptManager_Output", resourceCulture) ?? "Output";
        public static string ScriptManager_SearchPlaceholder => ResourceManager.GetString("ScriptManager_SearchPlaceholder", resourceCulture) ?? "Search scripts...";
        public static string ScriptManager_Reload => ResourceManager.GetString("ScriptManager_Reload", resourceCulture) ?? "Reload";
        public static string ScriptManager_Edit => ResourceManager.GetString("ScriptManager_Edit", resourceCulture) ?? "Edit";
        public static string ScriptManager_TriggerBuilderDesc => ResourceManager.GetString("ScriptManager_TriggerBuilderDesc", resourceCulture) ?? "Create automation triggers without writing code.";
        public static string ScriptManager_AddTrigger => ResourceManager.GetString("ScriptManager_AddTrigger", resourceCulture) ?? "+ Add Trigger";
        public static string ScriptManager_Ready => ResourceManager.GetString("ScriptManager_Ready", resourceCulture) ?? "Ready";
        public static string ScriptManager_UnsavedChanges => ResourceManager.GetString("ScriptManager_UnsavedChanges", resourceCulture) ?? "You have unsaved changes. Do you want to save them?";
        public static string ScriptManager_FileSaved => ResourceManager.GetString("ScriptManager_FileSaved", resourceCulture) ?? "File saved";
        public static string ScriptManager_EnterScriptName => ResourceManager.GetString("ScriptManager_EnterScriptName", resourceCulture) ?? "Enter script name:";
        public static string ScriptManager_EnterTriggerName => ResourceManager.GetString("ScriptManager_EnterTriggerName", resourceCulture) ?? "Enter trigger file name:";
        public static string ScriptManager_ConfirmDelete => ResourceManager.GetString("ScriptManager_ConfirmDelete", resourceCulture) ?? "Are you sure you want to delete {0}?";
        public static string ScriptManager_ConfirmDeleteTrigger => ResourceManager.GetString("ScriptManager_ConfirmDeleteTrigger", resourceCulture) ?? "Are you sure you want to delete this trigger?";
        public static string ScriptManager_AllReloaded => ResourceManager.GetString("ScriptManager_AllReloaded", resourceCulture) ?? "All scripts reloaded";
        
        // Trigger Builder
        public static string TriggerBuilder_Title => ResourceManager.GetString("TriggerBuilder_Title", resourceCulture) ?? "Trigger Builder";
        public static string TriggerBuilder_Description => ResourceManager.GetString("TriggerBuilder_Description", resourceCulture) ?? "Create automation rules without writing code";
        public static string TriggerBuilder_WhenEvent => ResourceManager.GetString("TriggerBuilder_WhenEvent", resourceCulture) ?? "When this happens:";
        public static string TriggerBuilder_MatchPattern => ResourceManager.GetString("TriggerBuilder_MatchPattern", resourceCulture) ?? "Match text (optional):";
        public static string TriggerBuilder_MatchPatternHint => ResourceManager.GetString("TriggerBuilder_MatchPatternHint", resourceCulture) ?? "Leave empty to trigger on all events of this type";
        public static string TriggerBuilder_MatchType => ResourceManager.GetString("TriggerBuilder_MatchType", resourceCulture) ?? "Match type:";
        public static string TriggerBuilder_ChannelFilter => ResourceManager.GetString("TriggerBuilder_ChannelFilter", resourceCulture) ?? "Channel filter (optional):";
        public static string TriggerBuilder_ChannelFilterHint => ResourceManager.GetString("TriggerBuilder_ChannelFilterHint", resourceCulture) ?? "Limit to specific channels. Use * for wildcard.";
        public static string TriggerBuilder_ThenAction => ResourceManager.GetString("TriggerBuilder_ThenAction", resourceCulture) ?? "Then do this:";
        public static string TriggerBuilder_Message => ResourceManager.GetString("TriggerBuilder_Message", resourceCulture) ?? "Message:";
        public static string TriggerBuilder_MessageHint => ResourceManager.GetString("TriggerBuilder_MessageHint", resourceCulture) ?? "Variables: {nick}, {channel}, {message}, {server}";
        public static string TriggerBuilder_TargetChannel => ResourceManager.GetString("TriggerBuilder_TargetChannel", resourceCulture) ?? "Target channel/user:";
        public static string TriggerBuilder_Command => ResourceManager.GetString("TriggerBuilder_Command", resourceCulture) ?? "Command to run:";
        public static string TriggerBuilder_CommandHint => ResourceManager.GetString("TriggerBuilder_CommandHint", resourceCulture) ?? "Example: /mode {channel} +o {nick}";
        public static string TriggerBuilder_Sound => ResourceManager.GetString("TriggerBuilder_Sound", resourceCulture) ?? "Sound:";
        public static string TriggerBuilder_Create => ResourceManager.GetString("TriggerBuilder_Create", resourceCulture) ?? "Create Trigger";
        public static string TriggerBuilder_Save => ResourceManager.GetString("TriggerBuilder_Save", resourceCulture) ?? "Save";
        
        // Common
        public static string Common_OK => ResourceManager.GetString("Common_OK", resourceCulture) ?? "OK";
        public static string Common_Cancel => ResourceManager.GetString("Common_Cancel", resourceCulture) ?? "Cancel";
        public static string Common_Close => ResourceManager.GetString("Common_Close", resourceCulture) ?? "Close";
        
        // FiSH Encryption
        public static string FiSH_SetKey => ResourceManager.GetString("FiSH_SetKey", resourceCulture) ?? "Set encryption key...";
        public static string FiSH_RemoveKey => ResourceManager.GetString("FiSH_RemoveKey", resourceCulture) ?? "Remove encryption key";
        public static string FiSH_ShowKey => ResourceManager.GetString("FiSH_ShowKey", resourceCulture) ?? "Show encryption key";
        public static string FiSH_KeyExchange => ResourceManager.GetString("FiSH_KeyExchange", resourceCulture) ?? "Key exchange (DH1080)";
        public static string FiSH_SetKeyTitle => ResourceManager.GetString("FiSH_SetKeyTitle", resourceCulture) ?? "Set FiSH Encryption Key";
        public static string FiSH_SetKeyPrompt => ResourceManager.GetString("FiSH_SetKeyPrompt", resourceCulture) ?? "Enter encryption key for {0}:";
        public static string FiSH_Encryption => ResourceManager.GetString("FiSH_Encryption", resourceCulture) ?? "Encryption";
        public static string Message_Encrypted => ResourceManager.GetString("Message_Encrypted", resourceCulture) ?? "This message was encrypted with FiSH";
    }
}
