//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Munin.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Munin.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munin IRC Client.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC Client.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        // Encryption Setup
        public static string EncryptionSetup_Title => ResourceManager.GetString("EncryptionSetup_Title", resourceCulture) ?? "";
        public static string EncryptionSetup_Header => ResourceManager.GetString("EncryptionSetup_Header", resourceCulture) ?? "";
        public static string EncryptionSetup_Description => ResourceManager.GetString("EncryptionSetup_Description", resourceCulture) ?? "";
        public static string EncryptionSetup_WillBeEncrypted => ResourceManager.GetString("EncryptionSetup_WillBeEncrypted", resourceCulture) ?? "";
        public static string EncryptionSetup_ServerConfigs => ResourceManager.GetString("EncryptionSetup_ServerConfigs", resourceCulture) ?? "";
        public static string EncryptionSetup_NickServSasl => ResourceManager.GetString("EncryptionSetup_NickServSasl", resourceCulture) ?? "";
        public static string EncryptionSetup_ChatHistory => ResourceManager.GetString("EncryptionSetup_ChatHistory", resourceCulture) ?? "";
        public static string EncryptionSetup_AllSettings => ResourceManager.GetString("EncryptionSetup_AllSettings", resourceCulture) ?? "";
        public static string EncryptionSetup_CreatePassword => ResourceManager.GetString("EncryptionSetup_CreatePassword", resourceCulture) ?? "";
        public static string EncryptionSetup_ConfirmPassword => ResourceManager.GetString("EncryptionSetup_ConfirmPassword", resourceCulture) ?? "";
        public static string EncryptionSetup_Warning => ResourceManager.GetString("EncryptionSetup_Warning", resourceCulture) ?? "";
        public static string EncryptionSetup_Enable => ResourceManager.GetString("EncryptionSetup_Enable", resourceCulture) ?? "";
        public static string EncryptionSetup_Skip => ResourceManager.GetString("EncryptionSetup_Skip", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordEmpty => ResourceManager.GetString("EncryptionSetup_PasswordEmpty", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordTooShort => ResourceManager.GetString("EncryptionSetup_PasswordTooShort", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordMismatch => ResourceManager.GetString("EncryptionSetup_PasswordMismatch", resourceCulture) ?? "";
        public static string EncryptionSetup_PasswordWeak => ResourceManager.GetString("EncryptionSetup_PasswordWeak", resourceCulture) ?? "";
        public static string EncryptionSetup_SkipConfirmTitle => ResourceManager.GetString("EncryptionSetup_SkipConfirmTitle", resourceCulture) ?? "";
        public static string EncryptionSetup_SkipConfirmMessage => ResourceManager.GetString("EncryptionSetup_SkipConfirmMessage", resourceCulture) ?? "";
        public static string EncryptionSetup_Failed => ResourceManager.GetString("EncryptionSetup_Failed", resourceCulture) ?? "";
        
        // Unlock Dialog
        public static string Unlock_Title => ResourceManager.GetString("Unlock_Title", resourceCulture) ?? "";
        public static string Unlock_Header => ResourceManager.GetString("Unlock_Header", resourceCulture) ?? "";
        public static string Unlock_Description => ResourceManager.GetString("Unlock_Description", resourceCulture) ?? "";
        public static string Unlock_MasterPassword => ResourceManager.GetString("Unlock_MasterPassword", resourceCulture) ?? "";
        public static string Unlock_Button => ResourceManager.GetString("Unlock_Button", resourceCulture) ?? "";
        public static string Unlock_ForgotPassword => ResourceManager.GetString("Unlock_ForgotPassword", resourceCulture) ?? "";
        public static string Unlock_ResetAll => ResourceManager.GetString("Unlock_ResetAll", resourceCulture) ?? "";
        public static string Unlock_EnterPassword => ResourceManager.GetString("Unlock_EnterPassword", resourceCulture) ?? "";
        public static string Unlock_WrongPassword => ResourceManager.GetString("Unlock_WrongPassword", resourceCulture) ?? "";
        public static string Unlock_TooManyAttempts => ResourceManager.GetString("Unlock_TooManyAttempts", resourceCulture) ?? "";
        public static string Unlock_AttemptsCount => ResourceManager.GetString("Unlock_AttemptsCount", resourceCulture) ?? "";
        public static string Unlock_ResetWarning => ResourceManager.GetString("Unlock_ResetWarning", resourceCulture) ?? "";
        public static string Unlock_ResetConfirmTitle => ResourceManager.GetString("Unlock_ResetConfirmTitle", resourceCulture) ?? "";
        public static string Unlock_ResetFinalConfirm => ResourceManager.GetString("Unlock_ResetFinalConfirm", resourceCulture) ?? "";
        
        // Main Window
        public static string MainWindow_AddServer => ResourceManager.GetString("MainWindow_AddServer", resourceCulture) ?? "";
        public static string MainWindow_JoinChannel => ResourceManager.GetString("MainWindow_JoinChannel", resourceCulture) ?? "";
        public static string MainWindow_SendMessage => ResourceManager.GetString("MainWindow_SendMessage", resourceCulture) ?? "";
        public static string MainWindow_Users => ResourceManager.GetString("MainWindow_Users", resourceCulture) ?? "";
        public static string MainWindow_Channels => ResourceManager.GetString("MainWindow_Channels", resourceCulture) ?? "";
        public static string MainWindow_Servers => ResourceManager.GetString("MainWindow_Servers", resourceCulture) ?? "";
        public static string MainWindow_Search => ResourceManager.GetString("MainWindow_Search", resourceCulture) ?? "";
        
        // Add Server Dialog
        public static string AddServer_Title => ResourceManager.GetString("AddServer_Title", resourceCulture) ?? "";
        public static string AddServer_ServerName => ResourceManager.GetString("AddServer_ServerName", resourceCulture) ?? "";
        public static string AddServer_Address => ResourceManager.GetString("AddServer_Address", resourceCulture) ?? "";
        public static string AddServer_Port => ResourceManager.GetString("AddServer_Port", resourceCulture) ?? "";
        public static string AddServer_UseSSL => ResourceManager.GetString("AddServer_UseSSL", resourceCulture) ?? "";
        public static string AddServer_Nickname => ResourceManager.GetString("AddServer_Nickname", resourceCulture) ?? "";
        public static string AddServer_Username => ResourceManager.GetString("AddServer_Username", resourceCulture) ?? "";
        public static string AddServer_RealName => ResourceManager.GetString("AddServer_RealName", resourceCulture) ?? "";
        public static string AddServer_Password => ResourceManager.GetString("AddServer_Password", resourceCulture) ?? "";
        public static string AddServer_AutoConnect => ResourceManager.GetString("AddServer_AutoConnect", resourceCulture) ?? "";
        public static string AddServer_Channels => ResourceManager.GetString("AddServer_Channels", resourceCulture) ?? "";
        
        // Settings Dialog
        public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture) ?? "";
        public static string Settings_General => ResourceManager.GetString("Settings_General", resourceCulture) ?? "";
        public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", resourceCulture) ?? "";
        public static string Settings_Security => ResourceManager.GetString("Settings_Security", resourceCulture) ?? "";
        public static string Settings_Notifications => ResourceManager.GetString("Settings_Notifications", resourceCulture) ?? "";
        public static string Settings_AutoLock => ResourceManager.GetString("Settings_AutoLock", resourceCulture) ?? "";
        public static string Settings_AutoLockMinutes => ResourceManager.GetString("Settings_AutoLockMinutes", resourceCulture) ?? "";
        public static string Settings_ChangePassword => ResourceManager.GetString("Settings_ChangePassword", resourceCulture) ?? "";
        public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture) ?? "";
        public static string Settings_ThemeDark => ResourceManager.GetString("Settings_ThemeDark", resourceCulture) ?? "";
        public static string Settings_ThemeLight => ResourceManager.GetString("Settings_ThemeLight", resourceCulture) ?? "";
        public static string Settings_FontSize => ResourceManager.GetString("Settings_FontSize", resourceCulture) ?? "";
        public static string Settings_Timestamps => ResourceManager.GetString("Settings_Timestamps", resourceCulture) ?? "";
        public static string Settings_DesktopNotifications => ResourceManager.GetString("Settings_DesktopNotifications", resourceCulture) ?? "";
        public static string Settings_SoundNotifications => ResourceManager.GetString("Settings_SoundNotifications", resourceCulture) ?? "";
        
        // Status Messages
        public static string Status_Connecting => ResourceManager.GetString("Status_Connecting", resourceCulture) ?? "";
        public static string Status_Connected => ResourceManager.GetString("Status_Connected", resourceCulture) ?? "";
        public static string Status_Disconnected => ResourceManager.GetString("Status_Disconnected", resourceCulture) ?? "";
        public static string Status_Reconnecting => ResourceManager.GetString("Status_Reconnecting", resourceCulture) ?? "";
        public static string Status_ConnectionFailed => ResourceManager.GetString("Status_ConnectionFailed", resourceCulture) ?? "";
        
        // Context Menu
        public static string ContextMenu_Copy => ResourceManager.GetString("ContextMenu_Copy", resourceCulture) ?? "";
        public static string ContextMenu_Paste => ResourceManager.GetString("ContextMenu_Paste", resourceCulture) ?? "";
        public static string ContextMenu_SelectAll => ResourceManager.GetString("ContextMenu_SelectAll", resourceCulture) ?? "";
        public static string ContextMenu_PrivateMessage => ResourceManager.GetString("ContextMenu_PrivateMessage", resourceCulture) ?? "";
        public static string ContextMenu_Whois => ResourceManager.GetString("ContextMenu_Whois", resourceCulture) ?? "";
        public static string ContextMenu_Kick => ResourceManager.GetString("ContextMenu_Kick", resourceCulture) ?? "";
        public static string ContextMenu_Ban => ResourceManager.GetString("ContextMenu_Ban", resourceCulture) ?? "";
        public static string ContextMenu_Op => ResourceManager.GetString("ContextMenu_Op", resourceCulture) ?? "";
        public static string ContextMenu_DeOp => ResourceManager.GetString("ContextMenu_DeOp", resourceCulture) ?? "";
        public static string ContextMenu_Voice => ResourceManager.GetString("ContextMenu_Voice", resourceCulture) ?? "";
        public static string ContextMenu_DeVoice => ResourceManager.GetString("ContextMenu_DeVoice", resourceCulture) ?? "";
    }
}
